[tool.poetry]
name = "task_manager"
version = "0.1.0"
description = ""
authors = ["altvec <me@sergeykalistratov.com>"]
license = "MIT"

[tool.poetry.dependencies]
python = "^3.6"
django = "^3.0.2"
python-dotenv = "^0.10.3"
django-bootstrap4 = "^1.1.1"
rollbar = "^0.14.7"
gunicorn = "^20.0.4"
whitenoise = "^5.0.1"

[tool.poetry.dev-dependencies]
wemake-python-styleguide = "^0.13.3"
pytest = "^5.3.4"

[build-system]
requires = ["poetry>=0.12"]
build-backend = "poetry.masonry.api"
