# Generated by Django 3.0.2 on 2020-02-05 12:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='status',
            field=models.CharField(choices=[('new', 'New task'), ('in_progress', 'In progress'), ('testing', 'In testing'), ('completed', 'Completed')], default='new', max_length=20),
        ),
    ]
